apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-web-app
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nodejs-app
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        envFrom:                    # ← injects ALL keys from the ConfigMap
            - configMapRef:
                name: my-app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
            