apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials-secret   # Referenced in django-deployment.yaml
  namespace: default
type: Opaque
immutable: true                       # Best practice: prevents accidental changes!
stringData:
  postgres-password: "SuperSecret123!"  # PostgreSQL POSTGRES_PASSWORD value
  postgres-user: "django_user"          # PostgreSQL POSTGRES_USER value
  postgres-db: "django_db"              # PostgreSQL POSTGRES_DB value